use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :mcam_server_web, McamServerWeb.Endpoint,
  url: [host: "mcam.iscodebaseonfire.com", scheme: "https", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [port: 80],
  https: [port: 443],
  force_ssl: [hsts: true],
  server: true

config :mcam_server, McamServer.Repo, prepare: :unnamed

config :logger, level: :info
